### PR TITLE
Add snapshot testing setup

### PR DESCRIPTION
**Pull request by AamirAlam**
## Changes
- Add snapshot test setup

- Homepage test result
homepagetest

- Navbar test result
navbar test

### CODE REVIEW

**Comment by AamirAlam** [comment]
@ArfatSalman  Stuck with snapshot testing issue with react-intl using enzyme. Working on few solutions to fix it

**Comment by AamirAlam** [comment]
@ArfatSalman  I have one doubt, do we need to add snapshot test for each component or for only the root component?

**Comment by ArfatSalman** [comment]
> @ArfatSalman I have one doubt, do we need to add snapshot test for each component or only for the root component?

Since the pipeline is established, you can skip snapshots tests now for any more components. We'll do the snapshots in the last week now when the design is finalised. For now, focus on E2E tests.

**Review by ArfatSalman — COMMENTED** [review]
Looks good.

**Comment by ArfatSalman** [comment]
Delete the branches once it is merged.

**Pull request merged**
